name: CD

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: ninaad98/cloudmart-api:latest
  RESOURCE_GROUP: Student-RG-1884880
  CONTAINER_GROUP: cloudmart-app
  LOCATION: canadaeast
  VNET_NAME: Student-1884880-vnet
  SUBNET_NAME: app-subnet

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ninaad98  
          password: dckr_pat_W99LPJzf10lCUZ7mF-xok6sxkCo

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Delete existing container group if it exists, ignore error if not
      - name: Delete existing container group (if any)
        continue-on-error: true
        run: |
          az container delete \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CONTAINER_GROUP }} \
            --yes

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.CONTAINER_GROUP }} \
            --image ${{ env.IMAGE_NAME }} \
            --location ${{ env.LOCATION }} \
            --restart-policy Always \
            --ports 80 \
            --vnet ${{ env.VNET_NAME }} \
            --subnet ${{ env.SUBNET_NAME }} \
            --environment-variables \
              COSMOS_ENDPOINT=${{ secrets.COSMOS_ENDPOINT }} \
              COSMOS_KEY=${{ secrets.COSMOS_KEY }}
